# Generated by Django 3.2.24 on 2025-08-19 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('line', 'Linha'), ('bar', 'Barras'), ('pie', 'Pizza'), ('doughnut', 'Rosquinha'), ('area', 'Área'), ('scatter', 'Dispersão')], max_length=20)),
                ('configuracao', models.JSONField(default=dict)),
                ('paleta_cores', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Configuração de Gráfico',
                'verbose_name_plural': 'Configurações de Gráficos',
            },
        ),
        migrations.CreateModel(
            name='ReportAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('threshold', 'Limite Atingido'), ('variation', 'Variação Significativa'), ('target', 'Meta Atingida'), ('anomaly', 'Anomalia Detectada')], max_length=20)),
                ('indicador', models.CharField(max_length=100)),
                ('condicao', models.JSONField(default=dict)),
                ('destinatarios', models.JSONField(default=list)),
                ('ativo', models.BooleanField(default=True)),
                ('ultima_verificacao', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Alerta de Relatório',
                'verbose_name_plural': 'Alertas de Relatórios',
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('mercado', 'Relatório de Mercado'), ('dashboard_executivo', 'Dashboard Executivo'), ('comparativo', 'Análise Comparativa'), ('tendencias', 'Análise de Tendências'), ('trimestral', 'Relatório Trimestral'), ('anual', 'Relatório Anual')], max_length=50)),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('html', 'HTML'), ('dashboard', 'Dashboard Interativo')], max_length=20)),
                ('configuracao', models.JSONField(default=dict)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Template de Relatório',
                'verbose_name_plural': 'Templates de Relatórios',
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('frequencia', models.CharField(choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('yearly', 'Anual')], max_length=20)),
                ('hora', models.TimeField(default='08:00')),
                ('dia_mes', models.IntegerField(blank=True, null=True)),
                ('destinatarios', models.JSONField(default=list)),
                ('ativo', models.BooleanField(default=True)),
                ('proximo_envio', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.reporttemplate')),
            ],
            options={
                'verbose_name': 'Agendamento de Relatório',
                'verbose_name_plural': 'Agendamentos de Relatórios',
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fim', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('error', 'Erro')], default='pending', max_length=20)),
                ('arquivo_path', models.CharField(blank=True, max_length=500)),
                ('parametros', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.reporttemplate')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relatório Gerado',
                'verbose_name_plural': 'Relatórios Gerados',
                'ordering': ['-created_at'],
            },
        ),
    ]
