# Generated by Django 3.2.24 on 2025-08-19 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARNQueryCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_hash', models.CharField(max_length=64, unique=True)),
                ('resultado', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('validade', models.IntegerField(default=3600)),
                ('hits', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Cache de Query ARN',
                'verbose_name_plural': 'Cache de Queries ARN',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inicio_sessao', models.DateTimeField(auto_now_add=True)),
                ('fim_sessao', models.DateTimeField(blank=True, null=True)),
                ('contexto', models.JSONField(default=dict)),
                ('ativa', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão de Chat',
                'verbose_name_plural': 'Sessões de Chat',
                'ordering': ['-inicio_sessao'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('user', 'Usuário'), ('bot', 'Bot'), ('system', 'Sistema')], max_length=10)),
                ('mensagem', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('intencao_detectada', models.CharField(blank=True, max_length=100, null=True)),
                ('confianca', models.FloatField(blank=True, null=True)),
                ('dados_resposta', models.JSONField(blank=True, null=True)),
                ('tempo_resposta', models.FloatField(blank=True, null=True)),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='dashboard.chatsession')),
            ],
            options={
                'verbose_name': 'Mensagem de Chat',
                'verbose_name_plural': 'Mensagens de Chat',
                'ordering': ['timestamp'],
            },
        ),
    ]
