# Generated by Django 3.2.24 on 2025-08-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_arnquerycache_chatmessage_chatsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('consulta_assinantes', 'Consulta de Assinantes'), ('analise_trafego', 'Análise de Tráfego'), ('mobile_money', 'Mobile Money'), ('market_share', 'Market Share'), ('tendencias', 'Análise de Tendências'), ('comparacao_operadores', 'Comparação de Operadores'), ('receitas', 'Análise de Receitas'), ('investimentos', 'Análise de Investimentos'), ('banda_larga', 'Banda Larga'), ('emprego', 'Análise de Emprego'), ('saudacao', 'Saudação'), ('despedida', 'Despedida'), ('nao_entendido', 'Não Entendido')], max_length=50)),
                ('palavras_chave', models.JSONField(default=list)),
                ('entidades_esperadas', models.JSONField(default=list)),
                ('template_resposta', models.TextField()),
                ('query_sql', models.TextField(blank=True)),
                ('confianca_minima', models.FloatField(default=0.7)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Intenção de Chat',
                'verbose_name_plural': 'Intenções de Chat',
            },
        ),
    ]
