# Generated by Django 3.2.24 on 2025-07-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0002_tarifariovoztelecelindicador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacoesmoveisindicador',
            name='banda_larga_movel',
        ),
        migrations.RemoveField(
            model_name='estacoesmoveisindicador',
            name='utilizadores_5g_upgrades',
        ),
        migrations.RemoveField(
            model_name='estacoesmoveisindicador',
            name='utilizadores_placas_box',
        ),
        migrations.RemoveField(
            model_name='estacoesmoveisindicador',
            name='utilizadores_placas_usb',
        ),
        migrations.RemoveField(
            model_name='estacoesmoveisindicador',
            name='utilizadores_servico_acesso_internet_banda_larga',
        ),
        migrations.AddField(
            model_name='estacoesmoveisindicador',
            name='utilizadores_3g_placas_box',
            field=models.IntegerField(default=0, help_text='dos quais com ligação através de Placas (Box) - 3G', verbose_name='3G - Placas (Box)'),
        ),
        migrations.AddField(
            model_name='estacoesmoveisindicador',
            name='utilizadores_3g_placas_usb',
            field=models.IntegerField(default=0, help_text='dos quais com ligação através de Placas (USB) - 3G', verbose_name='3G - Placas (USB)'),
        ),
        migrations.AddField(
            model_name='estacoesmoveisindicador',
            name='utilizadores_4g_placas_box',
            field=models.IntegerField(default=0, help_text='dos quais com ligação através de Placas (Box) - 4G', verbose_name='4G - Placas (Box)'),
        ),
        migrations.AddField(
            model_name='estacoesmoveisindicador',
            name='utilizadores_4g_placas_usb',
            field=models.IntegerField(default=0, help_text='dos quais com ligação através de Placas (USB) - 4G', verbose_name='4G - Placas (USB)'),
        ),
        migrations.AddField(
            model_name='estacoesmoveisindicador',
            name='utilizadores_acesso_internet_3g',
            field=models.IntegerField(default=0, help_text='Utilizadores de serviço de acesso à Internet em banda larga (3G)', verbose_name='Utilizadores acesso Internet banda larga (3G)'),
        ),
        migrations.AddField(
            model_name='estacoesmoveisindicador',
            name='utilizadores_acesso_internet_4g',
            field=models.IntegerField(default=0, help_text='Utilizadores do serviço de acesso à Internet em banda larga (4G)', verbose_name='Utilizadores acesso Internet banda larga (4G)'),
        ),
        migrations.AddField(
            model_name='estacoesmoveisindicador',
            name='utilizadores_servico_3g_upgrades',
            field=models.IntegerField(default=0, help_text='Utilizadores de serviço de 3G e upgrades', verbose_name='Utilizadores de serviço de 3G e upgrades'),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='mms',
            field=models.IntegerField(blank=True, null=True, verbose_name='MMS'),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='mobile_tv',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mobile TV'),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='roaming_internacional_out_parc_roaming_out',
            field=models.IntegerField(default=0, verbose_name='Roaming Internacional Out'),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='sms',
            field=models.IntegerField(default=0, verbose_name='SMS'),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='utilizadores_servico_4g',
            field=models.IntegerField(default=0, help_text='Utilizadores de serviço de 4G', verbose_name='Utilizadores de serviço de 4G'),
        ),
    ]
