# Generated by Django 3.2.24 on 2025-08-25 11:24

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0003_auto_20250710_1104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estacoesmoveisindicador',
            options={'ordering': ['-ano', '-mes', 'operadora'], 'verbose_name': 'Indicador de Estações Móveis', 'verbose_name_plural': 'Indicadores de Estações Móveis'},
        ),
        migrations.AddField(
            model_name='estacoesmoveisindicador',
            name='linhas_128kbit',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='4.1.2 Linhas 128 Kbit/s'),
        ),
        migrations.AddField(
            model_name='estacoesmoveisindicador',
            name='linhas_1mbit',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='4.1.5 Linhas 1 Mbit/s'),
        ),
        migrations.AddField(
            model_name='estacoesmoveisindicador',
            name='linhas_256kbit',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='4.1.3 Linhas 256 Kbit/s'),
        ),
        migrations.AddField(
            model_name='estacoesmoveisindicador',
            name='linhas_512kbit',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='4.1.4 Linhas 512 Kbit/s'),
        ),
        migrations.AddField(
            model_name='estacoesmoveisindicador',
            name='linhas_64kbit',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='4.1.1 Linhas 64 Kbit'),
        ),
        migrations.AddField(
            model_name='estacoesmoveisindicador',
            name='linhas_maior_2mbit',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='4.1.6 Linhas > 2 Mbit/s'),
        ),
        migrations.AlterField(
            model_name='assinantesindicador',
            name='operadora',
            field=models.CharField(blank=True, choices=[('orange', 'Orange'), ('telecel', 'TELECEL')], max_length=10, null=True, verbose_name='Operadora'),
        ),
        migrations.AlterField(
            model_name='empregoindicador',
            name='operadora',
            field=models.CharField(blank=True, choices=[('orange', 'Orange'), ('telecel', 'TELECEL')], max_length=10, null=True, verbose_name='Operadora'),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='afectos_planos_pos_pagos',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='1.1 Afectos a planos Pós-pagos'),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='afectos_planos_pos_pagos_utilizacao',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='1.1.a Com utilização efectiva (Pós-pagos)'),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='afectos_planos_pre_pagos',
            field=models.BigIntegerField(default=0, help_text='Valores em milhões de estações', validators=[django.core.validators.MinValueValidator(0)], verbose_name='1.2 Afectos a planos Pré-pagos'),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='afectos_planos_pre_pagos_utilizacao',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='1.2.a Com utilização efectiva (Pré-pagos)'),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='associados_situacoes_especificas',
            field=models.IntegerField(blank=True, help_text='NA se não aplicável', null=True, verbose_name='1.3 Associados a situações específicas'),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='mms',
            field=models.IntegerField(blank=True, help_text='NA se não aplicável', null=True, verbose_name='2.1.2 MMS'),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='mobile_tv',
            field=models.IntegerField(blank=True, help_text='NA se não aplicável', null=True, verbose_name='2.1.3 Mobile TV'),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='numero_utilizadores',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='3.1 Número de utilizadores Mobile Money'),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='numero_utilizadores_homem',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='3.1.2 Utilizadores Homem'),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='numero_utilizadores_mulher',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='3.1.1 Utilizadores Mulher'),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='operadora',
            field=models.CharField(blank=True, choices=[('orange', 'Orange'), ('telecel', 'TELECEL')], max_length=10, null=True, verbose_name='Operadora'),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='outros_residuais',
            field=models.IntegerField(blank=True, help_text='NA se não aplicável', null=True, verbose_name='1.4 Outros (residuais)'),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='roaming_internacional_out_parc_roaming_out',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='2.1.4 Roaming Internacional - OUT - PARC ROAMING OUT'),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='sms',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='2.1.1 SMS'),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='total_carregamentos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor monetário total dos carregamentos', max_digits=25, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='3.2 Total de carregamentos efectuados'),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='total_carregamentos_homem',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=25, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='3.2.2 Carregamentos Homem'),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='total_carregamentos_mulher',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=25, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='3.2.1 Carregamentos Mulher'),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='total_levantamentos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor monetário total dos levantamentos', max_digits=25, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='3.3 Total de levantamentos efectuados'),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='total_levantamentos_homem',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=25, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='3.3.2 Levantamentos Homem'),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='total_levantamentos_mulher',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=25, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='3.3.1 Levantamentos Mulher'),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='total_transferencias',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor monetário total das transferências', max_digits=25, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='3.4 Total de Transferências'),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='total_transferencias_homem',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=25, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='3.4.2 Transferências Homem'),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='total_transferencias_mulher',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=25, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='3.4.1 Transferências Mulher'),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='utilizadores_3g_placas_box',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='2.1.5.1.1.p Placas (Box) 3G'),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='utilizadores_3g_placas_usb',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='2.1.5.1.1.q Placas (USB) 3G'),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='utilizadores_4g_placas_box',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='2.1.5.2.1.p Placas (Box) 4G'),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='utilizadores_4g_placas_usb',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='2.1.5.2.1.q Placas (USB) 4G'),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='utilizadores_acesso_internet_3g',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='2.1.5.1.1 Utilizadores de acesso à Internet banda larga (3G)'),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='utilizadores_acesso_internet_4g',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='2.1.5.2.1 Utilizadores de acesso à Internet banda larga (4G)'),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='utilizadores_servico_3g_upgrades',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='2.1.5.1 Utilizadores de serviço de 3G e upgrades'),
        ),
        migrations.AlterField(
            model_name='estacoesmoveisindicador',
            name='utilizadores_servico_4g',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='2.1.5.2 Utilizadores de serviço de 4G'),
        ),
        migrations.AlterField(
            model_name='internetfixoindicador',
            name='operadora',
            field=models.CharField(blank=True, choices=[('orange', 'Orange'), ('telecel', 'TELECEL')], max_length=10, null=True, verbose_name='Operadora'),
        ),
        migrations.AlterField(
            model_name='investimentoindicador',
            name='operadora',
            field=models.CharField(blank=True, choices=[('orange', 'Orange'), ('telecel', 'TELECEL')], max_length=10, null=True, verbose_name='Operadora'),
        ),
        migrations.AlterField(
            model_name='lbiindicador',
            name='operadora',
            field=models.CharField(blank=True, choices=[('orange', 'Orange'), ('telecel', 'TELECEL')], max_length=10, null=True, verbose_name='Operadora'),
        ),
        migrations.AlterField(
            model_name='receitasindicador',
            name='operadora',
            field=models.CharField(blank=True, choices=[('orange', 'Orange'), ('telecel', 'TELECEL')], max_length=10, null=True, verbose_name='Operadora'),
        ),
        migrations.AlterField(
            model_name='receitasindicador',
            name='receitas_chamadas_telecel',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Para o operador da rede móvel TELECEL'),
        ),
        migrations.AlterField(
            model_name='tarifariovozorangeindicador',
            name='operadora',
            field=models.CharField(blank=True, choices=[('orange', 'Orange'), ('telecel', 'TELECEL')], max_length=10, null=True, verbose_name='Operadora'),
        ),
        migrations.AlterField(
            model_name='tarifariovoztelecelindicador',
            name='operadora',
            field=models.CharField(choices=[('orange', 'Orange'), ('telecel', 'TELECEL')], default='telecel', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='trafegointernetindicador',
            name='operadora',
            field=models.CharField(blank=True, choices=[('orange', 'Orange'), ('telecel', 'TELECEL')], max_length=10, null=True, verbose_name='Operadora'),
        ),
        migrations.AlterField(
            model_name='trafegooriginadoindicador',
            name='operadora',
            field=models.CharField(blank=True, choices=[('orange', 'Orange'), ('telecel', 'TELECEL')], max_length=10, null=True, verbose_name='Operadora'),
        ),
        migrations.AlterField(
            model_name='trafegoroaminginternacionalindicador',
            name='operadora',
            field=models.CharField(blank=True, choices=[('orange', 'Orange'), ('telecel', 'TELECEL')], max_length=10, null=True, verbose_name='Operadora'),
        ),
        migrations.AlterField(
            model_name='trafegoterminadoindicador',
            name='operadora',
            field=models.CharField(blank=True, choices=[('orange', 'Orange'), ('telecel', 'TELECEL')], max_length=10, null=True, verbose_name='Operadora'),
        ),
    ]
