# Generated by Django 3.2.24 on 2025-08-25 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0004_estacoes_moveis_updates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trafegooriginadoindicador',
            options={'ordering': ['-ano', '-mes', 'operadora'], 'verbose_name': 'Indicador de Tráfego Originado', 'verbose_name_plural': 'Indicadores de Tráfego Originado'},
        ),
        migrations.RemoveField(
            model_name='trafegooriginadoindicador',
            name='chamadas_internacional',
        ),
        migrations.RemoveField(
            model_name='trafegooriginadoindicador',
            name='chamadas_off_net',
        ),
        migrations.RemoveField(
            model_name='trafegooriginadoindicador',
            name='chamadas_telecel',
        ),
        migrations.RemoveField(
            model_name='trafegooriginadoindicador',
            name='internet_3g',
        ),
        migrations.RemoveField(
            model_name='trafegooriginadoindicador',
            name='internet_3g_modem_usb',
        ),
        migrations.RemoveField(
            model_name='trafegooriginadoindicador',
            name='internet_3g_placas_modem',
        ),
        migrations.RemoveField(
            model_name='trafegooriginadoindicador',
            name='internet_4g',
        ),
        migrations.RemoveField(
            model_name='trafegooriginadoindicador',
            name='internet_4g_modem_usb',
        ),
        migrations.RemoveField(
            model_name='trafegooriginadoindicador',
            name='internet_4g_placas_modem',
        ),
        migrations.RemoveField(
            model_name='trafegooriginadoindicador',
            name='operador_movel_b',
        ),
        migrations.RemoveField(
            model_name='trafegooriginadoindicador',
            name='operador_rede_fixa',
        ),
        migrations.RemoveField(
            model_name='trafegooriginadoindicador',
            name='sms_internacional',
        ),
        migrations.RemoveField(
            model_name='trafegooriginadoindicador',
            name='sms_off_net',
        ),
        migrations.RemoveField(
            model_name='trafegooriginadoindicador',
            name='trafego_dados_2g',
        ),
        migrations.RemoveField(
            model_name='trafegooriginadoindicador',
            name='trafego_dados_3g_upgrade',
        ),
        migrations.RemoveField(
            model_name='trafegooriginadoindicador',
            name='trafego_dados_4g',
        ),
        migrations.RemoveField(
            model_name='trafegooriginadoindicador',
            name='voz_cedeao',
        ),
        migrations.RemoveField(
            model_name='trafegooriginadoindicador',
            name='voz_cplp',
        ),
        migrations.RemoveField(
            model_name='trafegooriginadoindicador',
            name='voz_internacional',
        ),
        migrations.RemoveField(
            model_name='trafegooriginadoindicador',
            name='voz_off_net',
        ),
        migrations.RemoveField(
            model_name='trafegooriginadoindicador',
            name='voz_on_net',
        ),
        migrations.RemoveField(
            model_name='trafegooriginadoindicador',
            name='voz_palop',
        ),
        migrations.RemoveField(
            model_name='trafegooriginadoindicador',
            name='voz_resto_africa',
        ),
        migrations.RemoveField(
            model_name='trafegooriginadoindicador',
            name='voz_resto_mundo',
        ),
        migrations.RemoveField(
            model_name='trafegooriginadoindicador',
            name='voz_telecel',
        ),
        migrations.RemoveField(
            model_name='trafegooriginadoindicador',
            name='voz_total',
        ),
        migrations.AddField(
            model_name='trafegooriginadoindicador',
            name='chamadas_internacional_total',
            field=models.BigIntegerField(default=0, help_text='Total de chamadas internacionais', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.4.3 Chamadas Internacional Total'),
        ),
        migrations.AddField(
            model_name='trafegooriginadoindicador',
            name='chamadas_off_net_nacional',
            field=models.BigIntegerField(default=0, help_text='Chamadas para outras redes nacionais', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.4.2 Chamadas Off-net Nacional'),
        ),
        migrations.AddField(
            model_name='trafegooriginadoindicador',
            name='chamadas_outras_redes_moveis',
            field=models.BigIntegerField(default=0, help_text='Chamadas para outras operadoras móveis', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.4.2.2 Chamadas para Outras Redes Móveis'),
        ),
        migrations.AddField(
            model_name='trafegooriginadoindicador',
            name='chamadas_rede_fixa',
            field=models.BigIntegerField(default=0, help_text='Chamadas para rede fixa', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.4.2.1 Chamadas para Rede Fixa'),
        ),
        migrations.AddField(
            model_name='trafegooriginadoindicador',
            name='internet_3g_mbytes',
            field=models.BigIntegerField(default=0, help_text='Volume em MBytes', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.1.2.1 Internet 3G'),
        ),
        migrations.AddField(
            model_name='trafegooriginadoindicador',
            name='internet_3g_modem_usb_mbytes',
            field=models.BigIntegerField(default=0, help_text='Volume via Modem USB em MBytes', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.1.2.1.q Modem USB 3G'),
        ),
        migrations.AddField(
            model_name='trafegooriginadoindicador',
            name='internet_3g_placas_modem_mbytes',
            field=models.BigIntegerField(default=0, help_text='Volume via Placas/Modem em MBytes', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.1.2.1.p Placas/Modem 3G'),
        ),
        migrations.AddField(
            model_name='trafegooriginadoindicador',
            name='internet_4g_mbytes',
            field=models.BigIntegerField(default=0, help_text='Volume em MBytes', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.1.3.1 Internet 4G'),
        ),
        migrations.AddField(
            model_name='trafegooriginadoindicador',
            name='internet_4g_modem_usb_mbytes',
            field=models.BigIntegerField(default=0, help_text='Volume via Modem USB em MBytes', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.1.3.1.q Modem USB 4G'),
        ),
        migrations.AddField(
            model_name='trafegooriginadoindicador',
            name='internet_4g_modem_usb_sessoes',
            field=models.BigIntegerField(default=0, help_text='Sessões via Modem USB', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.1.3.1.q.a Sessões USB 4G'),
        ),
        migrations.AddField(
            model_name='trafegooriginadoindicador',
            name='internet_4g_placas_modem_mbytes',
            field=models.BigIntegerField(default=0, help_text='Volume via Placas/Modem em MBytes', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.1.3.1.p Placas/Modem 4G'),
        ),
        migrations.AddField(
            model_name='trafegooriginadoindicador',
            name='internet_4g_placas_modem_sessoes',
            field=models.BigIntegerField(default=0, help_text='Sessões via Placas/Modem', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.1.3.1.p.a Sessões Placas 4G'),
        ),
        migrations.AddField(
            model_name='trafegooriginadoindicador',
            name='internet_4g_sessoes',
            field=models.BigIntegerField(default=0, help_text='Número de sessões de Internet', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.1.3.1.a Sessões Internet 4G'),
        ),
        migrations.AddField(
            model_name='trafegooriginadoindicador',
            name='mms_total',
            field=models.BigIntegerField(blank=True, default=0, help_text='Total de MMS enviados', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.5.2 MMS Total'),
        ),
        migrations.AddField(
            model_name='trafegooriginadoindicador',
            name='sms_internacional_total',
            field=models.BigIntegerField(default=0, help_text='Total de SMS internacionais', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.2.3 SMS Internacional Total'),
        ),
        migrations.AddField(
            model_name='trafegooriginadoindicador',
            name='sms_off_net_nacional',
            field=models.BigIntegerField(default=0, help_text='SMS para outras redes nacionais', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.2.2 SMS Off-net Nacional'),
        ),
        migrations.AddField(
            model_name='trafegooriginadoindicador',
            name='trafego_dados_2g_mbytes',
            field=models.BigIntegerField(default=0, help_text='Volume em MBytes', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.1.1 Tráfego de Dados 2G'),
        ),
        migrations.AddField(
            model_name='trafegooriginadoindicador',
            name='trafego_dados_2g_sessoes',
            field=models.BigIntegerField(default=0, help_text='Número de sessões', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.1.1.a Sessões 2G'),
        ),
        migrations.AddField(
            model_name='trafegooriginadoindicador',
            name='trafego_dados_3g_upgrade_mbytes',
            field=models.BigIntegerField(default=0, help_text='Volume em MBytes', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.1.2 Tráfego de Dados 3G e upgrades'),
        ),
        migrations.AddField(
            model_name='trafegooriginadoindicador',
            name='trafego_dados_4g_mbytes',
            field=models.BigIntegerField(default=0, help_text='Volume em MBytes', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.1.3 Tráfego de Dados 4G'),
        ),
        migrations.AddField(
            model_name='trafegooriginadoindicador',
            name='trafego_dados_4g_sessoes',
            field=models.BigIntegerField(default=0, help_text='Número de sessões', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.1.3.a Sessões 4G'),
        ),
        migrations.AddField(
            model_name='trafegooriginadoindicador',
            name='voz_cedeao_minutos',
            field=models.BigIntegerField(default=0, help_text='Minutos para países da CEDEAO', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.3.3.1 Voz CEDEAO'),
        ),
        migrations.AddField(
            model_name='trafegooriginadoindicador',
            name='voz_cplp_minutos',
            field=models.BigIntegerField(default=0, help_text='Minutos para países CPLP', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.3.3.3 Voz CPLP'),
        ),
        migrations.AddField(
            model_name='trafegooriginadoindicador',
            name='voz_internacional_total_minutos',
            field=models.BigIntegerField(default=0, help_text='Total de minutos internacionais', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.3.3 Voz Internacional Total'),
        ),
        migrations.AddField(
            model_name='trafegooriginadoindicador',
            name='voz_off_net_nacional_minutos',
            field=models.BigIntegerField(default=0, help_text='Minutos para outras redes nacionais', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.3.2 Voz Off-net Nacional'),
        ),
        migrations.AddField(
            model_name='trafegooriginadoindicador',
            name='voz_on_net_minutos',
            field=models.BigIntegerField(default=0, help_text='Minutos dentro da mesma rede', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.3.1 Voz On-net'),
        ),
        migrations.AddField(
            model_name='trafegooriginadoindicador',
            name='voz_outras_redes_moveis_minutos',
            field=models.BigIntegerField(default=0, help_text='Minutos para outras operadoras móveis', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.3.2.2 Voz para Outras Redes Móveis'),
        ),
        migrations.AddField(
            model_name='trafegooriginadoindicador',
            name='voz_palop_minutos',
            field=models.BigIntegerField(default=0, help_text='Minutos para países PALOP', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.3.3.2 Voz PALOP'),
        ),
        migrations.AddField(
            model_name='trafegooriginadoindicador',
            name='voz_rede_fixa_minutos',
            field=models.BigIntegerField(default=0, help_text='Minutos para rede fixa', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.3.2.1 Voz para Rede Fixa'),
        ),
        migrations.AddField(
            model_name='trafegooriginadoindicador',
            name='voz_resto_africa_minutos',
            field=models.BigIntegerField(default=0, help_text='Minutos para outros países africanos', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.3.3.4 Voz Resto de África'),
        ),
        migrations.AddField(
            model_name='trafegooriginadoindicador',
            name='voz_resto_mundo_minutos',
            field=models.BigIntegerField(default=0, help_text='Minutos para resto do mundo', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.3.3.5 Voz Resto do Mundo'),
        ),
        migrations.AddField(
            model_name='trafegooriginadoindicador',
            name='voz_total_minutos',
            field=models.BigIntegerField(default=0, help_text='Volume total em minutos', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.3 Total de Minutos de Voz'),
        ),
        migrations.AlterField(
            model_name='trafegooriginadoindicador',
            name='chamadas_cedeao',
            field=models.BigIntegerField(default=0, help_text='Chamadas para países da CEDEAO', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.4.3.1 Chamadas CEDEAO'),
        ),
        migrations.AlterField(
            model_name='trafegooriginadoindicador',
            name='chamadas_cplp',
            field=models.BigIntegerField(default=0, help_text='Chamadas para países CPLP', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.4.3.3 Chamadas CPLP'),
        ),
        migrations.AlterField(
            model_name='trafegooriginadoindicador',
            name='chamadas_on_net',
            field=models.BigIntegerField(default=0, help_text='Chamadas dentro da mesma rede', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.4.1 Chamadas On-net'),
        ),
        migrations.AlterField(
            model_name='trafegooriginadoindicador',
            name='chamadas_palop',
            field=models.BigIntegerField(default=0, help_text='Chamadas para países PALOP', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.4.3.2 Chamadas PALOP'),
        ),
        migrations.AlterField(
            model_name='trafegooriginadoindicador',
            name='chamadas_resto_africa',
            field=models.BigIntegerField(default=0, help_text='Chamadas para outros países africanos', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.4.3.4 Chamadas Resto de África'),
        ),
        migrations.AlterField(
            model_name='trafegooriginadoindicador',
            name='chamadas_resto_mundo',
            field=models.BigIntegerField(default=0, help_text='Chamadas para resto do mundo', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.4.3.5 Chamadas Resto do Mundo'),
        ),
        migrations.AlterField(
            model_name='trafegooriginadoindicador',
            name='chamadas_total',
            field=models.BigIntegerField(default=0, help_text='Número total de chamadas', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.4 Total de Chamadas'),
        ),
        migrations.AlterField(
            model_name='trafegooriginadoindicador',
            name='internet_3g_modem_usb_sessoes',
            field=models.BigIntegerField(default=0, help_text='Sessões via Modem USB', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.1.2.1.q.a Sessões USB 3G'),
        ),
        migrations.AlterField(
            model_name='trafegooriginadoindicador',
            name='internet_3g_placas_modem_sessoes',
            field=models.BigIntegerField(default=0, help_text='Sessões via Placas/Modem', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.1.2.1.p.a Sessões Placas 3G'),
        ),
        migrations.AlterField(
            model_name='trafegooriginadoindicador',
            name='internet_3g_sessoes',
            field=models.BigIntegerField(default=0, help_text='Número de sessões de Internet', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.1.2.1.a Sessões Internet 3G'),
        ),
        migrations.AlterField(
            model_name='trafegooriginadoindicador',
            name='numeros_curtos',
            field=models.BigIntegerField(blank=True, default=0, help_text='Chamadas/SMS para números curtos', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.5.1 Números Curtos'),
        ),
        migrations.AlterField(
            model_name='trafegooriginadoindicador',
            name='sms_cedeao',
            field=models.BigIntegerField(default=0, help_text='SMS para países da CEDEAO', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.2.3.1 SMS CEDEAO'),
        ),
        migrations.AlterField(
            model_name='trafegooriginadoindicador',
            name='sms_cplp',
            field=models.BigIntegerField(default=0, help_text='SMS para países CPLP', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.2.3.3 SMS CPLP'),
        ),
        migrations.AlterField(
            model_name='trafegooriginadoindicador',
            name='sms_on_net',
            field=models.BigIntegerField(default=0, help_text='SMS dentro da mesma rede', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.2.1 SMS On-net'),
        ),
        migrations.AlterField(
            model_name='trafegooriginadoindicador',
            name='sms_palop',
            field=models.BigIntegerField(default=0, help_text='SMS para países PALOP', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.2.3.2 SMS PALOP'),
        ),
        migrations.AlterField(
            model_name='trafegooriginadoindicador',
            name='sms_resto_africa',
            field=models.BigIntegerField(default=0, help_text='SMS para outros países africanos', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.2.3.4 SMS Resto de África'),
        ),
        migrations.AlterField(
            model_name='trafegooriginadoindicador',
            name='sms_resto_mundo',
            field=models.BigIntegerField(default=0, help_text='SMS para resto do mundo', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.2.3.5 SMS Resto do Mundo'),
        ),
        migrations.AlterField(
            model_name='trafegooriginadoindicador',
            name='sms_total',
            field=models.BigIntegerField(default=0, help_text='Número total de mensagens enviadas', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.2 Total de SMS'),
        ),
        migrations.AlterField(
            model_name='trafegooriginadoindicador',
            name='trafego_dados_3g_upgrade_sessoes',
            field=models.BigIntegerField(default=0, help_text='Número de sessões', validators=[django.core.validators.MinValueValidator(0)], verbose_name='5.1.2.a Sessões 3G'),
        ),
    ]
