# Generated by Django 3.2.25
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='operadoras/logos/')),
                ('website', models.URLField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DadoEstatistico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_insercao', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('operadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados', to='home.operadora')),
                ('tipo_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tiposervico')),
            ],
            options={
                'ordering': ['-data_referencia', 'operadora'],
                'unique_together': {('operadora', 'tipo_servico', 'data_referencia')},
            },
        ),
    ] 