# Generated by Django 3.2.24 on 2025-08-19 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dadoestatistico',
            options={'verbose_name': 'Dado Estatístico', 'verbose_name_plural': 'Dados Estatísticos'},
        ),
        migrations.AlterModelOptions(
            name='operadora',
            options={'verbose_name': 'Operadora', 'verbose_name_plural': 'Operadoras'},
        ),
        migrations.AlterModelOptions(
            name='tiposervico',
            options={'verbose_name': 'Tipo de Serviço', 'verbose_name_plural': 'Tipos de Serviços'},
        ),
        migrations.RenameField(
            model_name='operadora',
            old_name='ativo',
            new_name='ativa',
        ),
        migrations.RemoveField(
            model_name='operadora',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='operadora',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='operadora',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='operadora',
            name='website',
        ),
        migrations.RemoveField(
            model_name='tiposervico',
            name='codigo',
        ),
        migrations.AddField(
            model_name='dadoestatistico',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dadoestatistico',
            name='unidade',
            field=models.CharField(default='Unidade', max_length=50),
        ),
        migrations.AddField(
            model_name='operadora',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tiposervico',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dadoestatistico',
            name='operadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.operadora'),
        ),
        migrations.AlterField(
            model_name='operadora',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='dadoestatistico',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('data_upload', 'Upload de Dados'), ('report_generate', 'Geração de Relatório'), ('data_analysis', 'Análise de Dados')], max_length=20)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atividade do Usuário',
                'verbose_name_plural': 'Atividades dos Usuários',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Informação'), ('success', 'Sucesso'), ('warning', 'Aviso'), ('error', 'Erro')], default='info', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='dadoestatistico',
            name='data_insercao',
        ),
        migrations.RemoveField(
            model_name='dadoestatistico',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='dadoestatistico',
            name='ultima_atualizacao',
        ),
    ]
